import type { Metadata } from "next";
import { Manrope, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "@/components/BottomNav";
import TopNav from "@/components/TopNav";
import Providers from "./providers";
import ClientShell from "@/components/ClientShell";

const geistSans = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cj ai l erreurreate Next App",
  description: "Generated by create next app",
};

// Rendre toute l'appli dynamique par défaut (pas de SSG / pas de cache Next)
// Conseil: laisser les pages par défaut en cache Next/SSG pour de meilleures perfs.
// Les pages qui doivent être temps réel déclarent leur propre `dynamic = "force-dynamic"`.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="dark">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
  <link rel="manifest" href="/manifest.json" />
  <meta name="theme-color" content="#0b1220" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white transition-colors duration-500`}>
        <Providers>
          <div className="transition-opacity duration-500" style={{minHeight:'100vh'}}>
            <ClientShell>{children}</ClientShell>
          </div>
        </Providers>
      </body>
    </html>
  );
}
